# Generated by Django 4.2.1 on 2023-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_incubatordb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incubatordb',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='incubatordb',
            name='ideation_count',
        ),
        migrations.RemoveField(
            model_name='incubatordb',
            name='incubation_count',
        ),
        migrations.RemoveField(
            model_name='incubatordb',
            name='industrialized_count',
        ),
        migrations.RemoveField(
            model_name='incubatordb',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='incubatordb',
            name='optimised_count',
        ),
        migrations.RemoveField(
            model_name='incubatordb',
            name='scaling_count',
        ),
        migrations.AlterField(
            model_name='incubatordb',
            name='components',
            field=models.CharField(choices=[['ideation', 'Ideation'], ['incubation', 'Incubation'], ['scaling', 'Scaling'], ['industrialized', 'Industrialized'], ['optimised', 'Optimised']], max_length=100),
        ),
        migrations.AlterField(
            model_name='incubatordb',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('delayed', 'Delayed'), ('warning', 'Warning'), ('stopped', 'Stopped')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incubatordb',
            name='type',
            field=models.CharField(choices=[('evolution_platform', 'Evolution Platform'), ('smart_industries', 'Smart Industries'), ('augmented_customer_exp', 'Augmented Customer Experience'), ('workplace_together', 'Workplace Together'), ('impactful_data', 'Impactful Data'), ('tools_for_ops', 'Tools for Operations')], max_length=50),
        ),
    ]
